python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_96_TSFusion \
  --model TSFusion \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 256 \
  --n_heads 8 \
  --d_ff 1024 \
  --dropout 0.1 \
  --des 'TSFusion_Experiment' \
  --itr 1 \
  --train_epochs 10 \
  --batch_size 32 \
  --learning_rate 0.001